version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.33-stretch
    steps:
      - checkout
      - run: |
          cargo build --release
          mkdir artifacts
      - store_artifacts:
          path: target/release/awall-config-back
          destination: artifacts/awall-config-back

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=latest
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

