version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.33-stretch
    steps:
      - checkout
      - run: |
          cargo build --release
          mkdir artifacts
          cp target/release/awall-config-back artifacts/
      - store_artifacts:
          path: target/release/awall-config-back
          destination: artifacts/awall-config-back
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - ./artifacts

  publish-github-release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=latest
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/workspace/artifacts

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build

